'use client';
import Link from 'next/link';
import { Heart, Menu, Search, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { FloatingCart } from '@/components/FloatingCart';
const links=[['Каталог','/catalog'],['О бренде','/about'],['Доставка','/delivery'],['Контакты','/contacts']];
export function Header(){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll);return()=>window.removeEventListener('scroll',onScroll)},[]);return <><header className={`sticky top-0 z-40 transition-all duration-300 ${scrolled?'pt-3':'border-b border-black/5 bg-cream/95'}`}><div className={`container transition-all duration-300 ${scrolled?'max-w-[1160px]':''}`}><div className={`flex items-center justify-between bg-cream/95 backdrop-blur transition-all duration-300 ${scrolled?'h-16 rounded-full border border-ink/10 px-5 shadow-soft':'h-20'}`}><button className="md:hidden" onClick={()=>setOpen(!open)} aria-label="Меню">{open?<X/>:<Menu/>}</button><Link href="/" className="font-serif text-3xl font-semibold tracking-[.15em]">TÖPP</Link><nav className="hidden gap-7 text-xs font-bold uppercase tracking-widest md:flex">{links.map(([n,h])=><Link key={h} href={h} className="hover:text-terra">{n}</Link>)}</nav><div className="flex items-center gap-4"><Search size={19}/><Link href="/favorites" aria-label="Избранное"><Heart size={19}/></Link></div></div></div></header>{open&&<nav className="fixed inset-x-4 top-24 z-30 rounded-3xl bg-cream p-6 shadow-soft md:hidden">{links.map(([n,h])=><Link onClick={()=>setOpen(false)} key={h} href={h} className="block border-b border-black/10 py-4 text-lg">{n}</Link>)}</nav>}</>}
export function FloatingBasket(){return <FloatingCart/>}
export function Footer(){return <footer className="bg-ink py-14 text-cream"><div className="container grid gap-10 md:grid-cols-4"><div><div className="font-serif text-3xl tracking-[.15em]">TÖPP</div><p className="mt-4 max-w-52 text-sm leading-6 text-cream/70">Тепло начинается с пола.</p></div><div><b className="text-xs uppercase tracking-widest">Покупателям</b><p className="mt-4 text-sm leading-8 text-cream/70">Доставка и оплата<br/>Возврат<br/>Уход за коврами</p></div><div><b className="text-xs uppercase tracking-widest">Контакты</b><p className="mt-4 text-sm leading-8 text-cream/70">+7 (800) 555-20-20<br/>hello@topp-rugs.ru<br/>Ежедневно 9:00–21:00</p></div><div><b className="text-xs uppercase tracking-widest">Письма о доме</b><p className="mt-4 text-sm text-cream/70">Идеи для уютного интерьера раз в месяц.</p><div className="mt-4 flex"><input className="w-full bg-white/10 px-3 text-sm outline-none" placeholder="Ваш e-mail"/><button className="bg-terra px-4 py-3 text-xs font-bold">→</button></div></div></div><div className="container mt-12 border-t border-white/10 pt-5 text-xs text-cream/45">© 2026 TÖPP. Дизайн-проект интернет-магазина ковров.</div></footer>}
