'use client';

import { useMemo, useState } from 'react';
import { ChevronDown, RotateCcw, SlidersHorizontal, X } from 'lucide-react';
import { products } from '@/lib/products';
import { ProductCard } from '@/components/ProductCard';
import { SelectMenu } from '@/components/SelectMenu';

const colors=['#F7F4EE','#E8DCC7','#D9C8B4','#C5A67B','#B86D52','#A44E39','#8A5A44','#879481','#617266','#A9B5A3','#7396A8','#4E6C82','#596073','#363A39','#808080','#B7A69B','#E7C5B4','#E2B7C5','#C8B0D8','#F2D168'];
const styles=['Все','Современный','Классический','Круглый','Детский'];
const countries=['Все страны','Турция','Бельгия','Индия','Египет','Иран'];
const sorting=['Популярные','Новинки','Сначала дешевле','Сначала дороже','По размеру','По скидке'];
const sizes=['Любой размер','120 × 170 см','140 × 200 см','160 × 230 см','200 × 300 см','240 × 340 см'];
function FilterTitle({children}:{children:React.ReactNode}){return <p className="mb-3 text-xs font-bold uppercase tracking-[.12em] text-ink">{children}</p>}
function Field({label,value,unit,onChange}:{label:string;value:string;unit:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-[11px] font-medium text-ink/50">{label}</span><div className="flex items-center rounded-2xl border border-ink/10 bg-cream px-3 py-1 transition focus-within:border-terra"><input value={value} onChange={e=>onChange(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="—" className="w-full bg-transparent py-2 text-sm font-bold outline-none"/><span className="text-xs text-ink/45">{unit}</span></div></label>}
export default function Catalog(){const [open,setOpen]=useState(false);const [style,setStyle]=useState('Все');const [country,setCountry]=useState('Все страны');const [sort,setSort]=useState('Популярные');const [minPrice,setMinPrice]=useState('');const [maxPrice,setMaxPrice]=useState('');const [size,setSize]=useState('Любой размер');const [length,setLength]=useState('');const [width,setWidth]=useState('');const [selectedColors,setSelectedColors]=useState<string[]>([]);
const items=useMemo(()=>{let list=style==='Все'?products:products.filter(x=>x.style===style);const min=Number(minPrice)||0,max=Number(maxPrice)||Infinity;list=list.filter(x=>x.price>=min&&x.price<=max);if(sort==='Сначала дешевле')return [...list].sort((a,b)=>a.price-b.price);if(sort==='Сначала дороже')return [...list].sort((a,b)=>b.price-a.price);return list},[style,minPrice,maxPrice,sort]);
const reset=()=>{setStyle('Все');setCountry('Все страны');setSort('Популярные');setMinPrice('');setMaxPrice('');setSize('Любой размер');setLength('');setWidth('');setSelectedColors([])};
const filters=<aside className={`${open?'block':'hidden'} lg:block`}><div className="rounded-[26px] bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><b className="font-serif text-2xl">Фильтры</b><button onClick={reset} className="flex items-center gap-1 text-xs text-terra"><RotateCcw size={13}/> Сбросить</button></div><div className="mt-7 border-t border-ink/10 pt-5"><FilterTitle>Стиль</FilterTitle><div className="flex flex-wrap gap-2">{styles.map(v=><button key={v} onClick={()=>setStyle(v)} className={`rounded-full px-3 py-2 text-xs ${style===v?'bg-ink text-white':'bg-cream text-ink/70'}`}>{v}</button>)}</div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Размер ковра</FilterTitle><SelectMenu value={size} options={sizes} onChange={setSize}/><div className="my-4 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.12em] text-ink/35"><span className="h-px flex-1 bg-ink/10"/>или укажите<span className="h-px flex-1 bg-ink/10"/></div><div className="grid grid-cols-2 gap-3"><Field label="Длина" value={length} unit="см" onChange={setLength}/><Field label="Ширина" value={width} unit="см" onChange={setWidth}/></div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Цена</FilterTitle><div className="grid grid-cols-2 gap-3"><Field label="От" value={minPrice} unit="₽" onChange={setMinPrice}/><Field label="До" value={maxPrice} unit="₽" onChange={setMaxPrice}/></div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Цвет</FilterTitle><div className="flex flex-wrap gap-1.5">{colors.map(c=><button key={c} onClick={()=>setSelectedColors(a=>a.includes(c)?a.filter(x=>x!==c):[...a,c])} style={{background:c}} aria-label={`Цвет ${c}`} className={`h-6 w-6 rounded-full border border-black/15 ${selectedColors.includes(c)?'ring-2 ring-terra ring-offset-2':''}`}/>)}</div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Страна производства</FilterTitle><SelectMenu value={country} options={countries} onChange={setCountry}/></div></div></aside>;
return <div className="container py-12 md:py-16"><p className="eyebrow">Коллекция TÖPP</p><h1 className="mt-3 text-5xl md:text-6xl">Все ковры</h1><div className="mt-10 rounded-[24px] border border-ink/10 bg-white p-3 shadow-soft md:flex md:items-center md:justify-between"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between rounded-2xl bg-cream px-4 py-3 text-sm font-bold md:w-auto"><span className="flex items-center gap-2"><SlidersHorizontal size={17}/> Фильтры и подбор</span>{open?<X size={17}/>:<ChevronDown size={17}/>}</button><div className="mt-3 flex items-center justify-between gap-4 px-2 md:mt-0"><span className="text-xs text-black/50">Найдено: {items.length}</span><div className="w-48"><SelectMenu compact value={sort} options={sorting} onChange={setSort}/></div></div></div><div className="mt-8 grid gap-8 lg:grid-cols-[310px_1fr]">{filters}<div className="grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div>}
