'use client';

import { useMemo, useState } from 'react';
import { ChevronDown, RotateCcw, SlidersHorizontal, X } from 'lucide-react';
import { products } from '@/lib/products';
import { ProductCard } from '@/components/ProductCard';

const colors = ['#F7F4EE','#E8DCC7','#D9C8B4','#C5A67B','#B86D52','#A44E39','#8A5A44','#879481','#617266','#A9B5A3','#7396A8','#4E6C82','#596073','#363A39','#808080','#B7A69B','#E7C5B4','#E2B7C5','#C8B0D8','#F2D168'];
const styles = ['Все', 'Современный', 'Классический', 'Круглый', 'Детский'];
const countries = ['Все страны', 'Турция', 'Бельгия', 'Индия', 'Египет', 'Иран'];
const sorting = ['Популярные', 'Новинки', 'Сначала дешевле', 'Сначала дороже', 'По размеру', 'По скидке'];

function FilterTitle({children}:{children:React.ReactNode}) { return <p className="mb-4 text-xs font-bold uppercase tracking-[.12em] text-ink">{children}</p> }
function RangeControl({label,value,onChange,max=400}:{label:string;value:number;onChange:(n:number)=>void;max?:number}) { return <label className="block text-xs text-black/55"><span className="mb-2 block">{label}</span><input className="filter-range w-full accent-terra" type="range" min="0" max={max} step="10" value={value} onChange={e=>onChange(Number(e.target.value))}/><span className="mt-2 block rounded-xl bg-cream px-3 py-2 text-sm font-bold text-ink">{value || 'Любой'} см</span></label> }

export default function Catalog(){
 const [open,setOpen]=useState(false); const [style,setStyle]=useState('Все'); const [country,setCountry]=useState('Все страны'); const [sort,setSort]=useState('Популярные'); const [minPrice,setMinPrice]=useState(0); const [maxPrice,setMaxPrice]=useState(25000); const [length,setLength]=useState(0); const [width,setWidth]=useState(0); const [selectedColors,setSelectedColors]=useState<string[]>([]);
 const items=useMemo(()=>{let list=style==='Все'?products:products.filter(x=>x.style===style); list=list.filter(x=>x.price>=minPrice&&x.price<=maxPrice); if(sort==='Сначала дешевле')list=[...list].sort((a,b)=>a.price-b.price);if(sort==='Сначала дороже')list=[...list].sort((a,b)=>b.price-a.price);if(sort==='По скидке')list=[...list].sort((a,b)=>(b.oldPrice||b.price)-b.price-((a.oldPrice||a.price)-a.price));return list},[style,minPrice,maxPrice,sort]);
 const reset=()=>{setStyle('Все');setCountry('Все страны');setMinPrice(0);setMaxPrice(25000);setLength(0);setWidth(0);setSelectedColors([]);};
 const filters=<aside className={`${open?'block':'hidden'} lg:block`}><div className="rounded-[24px] bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><b className="font-serif text-2xl">Фильтры</b><button onClick={reset} className="flex items-center gap-1 text-xs text-terra"><RotateCcw size={13}/> Сбросить</button></div><div className="mt-7 border-t border-ink/10 pt-5"><FilterTitle>Стиль</FilterTitle><div className="flex flex-wrap gap-2">{styles.map(v=><button key={v} onClick={()=>setStyle(v)} className={`rounded-full px-3 py-2 text-xs ${style===v?'bg-ink text-white':'bg-cream text-ink/70'}`}>{v}</button>)}</div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Размер, см</FilterTitle><div className="grid grid-cols-2 gap-4"><RangeControl label="Длина" value={length} onChange={setLength}/><RangeControl label="Ширина" value={width} onChange={setWidth}/></div><p className="mt-3 text-[11px] leading-4 text-black/45">Передвигайте ползунки, чтобы задать нужный размер.</p></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Цена, ₽</FilterTitle><div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-black/50">От<input type="number" value={minPrice} min="0" max={maxPrice} onChange={e=>setMinPrice(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-ink/10 bg-cream px-3 py-2 text-sm text-ink outline-none"/></label><label className="text-[11px] text-black/50">До<input type="number" value={maxPrice} min={minPrice} onChange={e=>setMaxPrice(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-ink/10 bg-cream px-3 py-2 text-sm text-ink outline-none"/></label></div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Цвет</FilterTitle><div className="grid grid-cols-5 gap-2">{colors.map(c=><button key={c} onClick={()=>setSelectedColors(a=>a.includes(c)?a.filter(x=>x!==c):[...a,c])} style={{background:c}} aria-label={`Выбрать цвет ${c}`} className={`h-7 w-7 rounded-full border ${selectedColors.includes(c)?'ring-2 ring-terra ring-offset-2':'border-black/15'}`}/>)}</div></div><div className="mt-6 border-t border-ink/10 pt-5"><FilterTitle>Страна производства</FilterTitle><select value={country} onChange={e=>setCountry(e.target.value)} className="w-full appearance-none rounded-xl border border-ink/10 bg-cream px-3 py-3 text-sm outline-none">{countries.map(x=><option key={x}>{x}</option>)}</select></div></div></aside>;
 return <div className="container py-12 md:py-16"><p className="eyebrow">Коллекция TÖPP</p><h1 className="mt-3 text-5xl md:text-6xl">Все ковры</h1><div className="mt-10 rounded-[24px] border border-ink/10 bg-white p-3 shadow-soft md:flex md:items-center md:justify-between"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between rounded-2xl bg-cream px-4 py-3 text-sm font-bold md:w-auto"><span className="flex items-center gap-2"><SlidersHorizontal size={17}/> Фильтры и подбор</span>{open?<X size={17}/>:<ChevronDown size={17}/>}</button><div className="mt-3 flex items-center justify-between gap-4 px-2 md:mt-0"><span className="text-xs text-black/50">Найдено: {items.length}</span><label className="flex items-center gap-2 text-xs text-black/55">Сортировка<select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl bg-sand/30 px-3 py-2 text-xs font-bold text-ink outline-none">{sorting.map(x=><option key={x}>{x}</option>)}</select></label></div></div><div className="mt-8 grid gap-8 lg:grid-cols-[310px_1fr]">{filters}<div className="grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div>
}
